name: App CI/CD

on:
  push:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4.1.0
        with:
          java-version: "18"
          distribution: "adopt"
          cache: maven
        
      - name: Test code
        working-directory: app
        run: mvn test

      - name: Build with Maven
        working-directory: app
        run: mvn clean install

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: app
          path: app/target/TwitchDiscordBridge-*.jar

  build-and-push-web-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, front]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Lower
        id: lowered
        uses: profy12/lowercase-action@0.6
        with:
          text: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lowered.outputs.text }}/twitch-discord-${{ matrix.service }}:latest

  build-and-push-app-image:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0

      - name: Download build artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: app
          path: target

      - name: Lower
        id: lowered
        uses: profy12/lowercase-action@0.6
        with:
          text: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.lowered.outputs.text }}/twitch-discord-bridge:latest
          build-args: |
            JAR_FILE=target/TwitchDiscordBridge-*.jar