name: CI/CD Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "adopt"
          cache: maven

      - name: Test code
        run: mvn test

      - name: Build with Maven
        run: mvn clean install

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/TwitchDiscordBridge-*.jar

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: app
          path: target

      - name: Lower
        id: lowered
        uses: profy12/lowercase-action@0.6
        with:
          text: ${{ github.repository_owner }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ steps.lowered.outputs.text }}/twitch-discord-bridge:latest
          build-args: |
            JAR_FILE=target/TwitchDiscordBridge-*.jar
